name: "BarcodeScanner"
services:
  db:
    container_name: db
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: melker
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  adminer:
    container_name: sigma
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
